---
  - name: restart docker daemon
    service:
     name: docker
     state: restarted
    tags:
     - docker
  - name: "get docker info"
    shell: docker info
    register: docker_info
    changed_when: false
    tags:
     - docker
  - name: init swarm
    shell: docker swarm init
    when: "docker_info.stdout.find('Swarm: inactive') != -1"
    tags:
     - docker