---
  - name: Add the user
    user:
     name: '{{username}}'
     comment: the user builder
     uid: 1001
     #die wheel group ist bei centos automatisch mit sudo rechten in /etc/sudoers ausgestattet
     groups: wheel
     password: '{{password}}'
    tags:
     - builduser              
