---
- name: Install K3s Agent and Join Cluster
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 \
    K3S_TOKEN={{ k3s_token }} sh -s - agent \
    --node-ip {{ ansible_host }}
  args:
    creates: /etc/rancher/k3s/config.yaml.d
