---
# tasks file for myfinance
 - name: modify vm.max_map_count for elasticSearch(reboot necessary)
   lineinfile:
    path: '/etc/sysctl.conf'
    state: present
    line: 'vm.max_map_count=262144'
   tags:
    - mf  
 - name: create dir for docker
   file: path=/home/{{username}}/docker 
    state=directory
   tags:
    - mf
 - name: create dir for fm docker compose
   file: path=/home/{{username}}/docker/mf
    state=directory
   tags:
    - mf
 - name: copy docker compose file
   template:
    src: myfinance-compose.yml.j2
    dest: "/home/{{username}}/docker/mf/docker-compose.yml"
    owner: "{{username}}"
   tags:
    - mf
#install myfinance to be sure that volumes are created
 - name: run the service for mf defined in docker-compose.yml
   shell: docker stack deploy -c /home/{{username}}/docker/mf/docker-compose.yml myfinance
   tags:
    - mf
 - name: copy keystore
   copy:
    src: prodkeystore.jks
    dest: "/var/lib/docker/volumes/myfinance_myfinanceconfig/_data/{{mf.ssl_keystore}}"
    mode: 0755
   tags:
    - mf
 - name: copy dac.res
   template:
    src: dac.res.j2
    dest: "/var/lib/docker/volumes/myfinance_myfinanceconfig/_data/dac.res"
   tags:
    - mf
 - name: remove mf service
   shell: docker stack rm myfinance && sleep 20
   tags:
    - mf
 - name: run the service for mf defined in docker-compose.yml
   shell: docker stack deploy -c /home/{{username}}/docker/mf/docker-compose.yml myfinance
   tags:
    - mf

