---
# tasks file for cicd
  - name: install tekton
    shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.30.0/release.yaml
    tags:
     - cicd
  - name: install tekton dashboard
    shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.22.0/tekton-dashboard-release.yaml
    tags:
     - cicd   
  - name: install tekton cli
    shell: curl -LO https://github.com/tektoncd/cli/releases/download/v0.24.0/tkn_0.24.0_Linux_x86_64.tar.gz && tar xvzf tkn_0.24.0_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn
    tags:
     - cicd 
     
  - name: Create symbolic link 
    file:
     src: "/usr/local/bin/tkn"
     dest: "/usr/local/bin/kubectl-tkn"
     state: link
    tags:
     - cicd        
          
#  - name: Add tekton cli as a kubectl plugin
#    shell: ln -s /usr/local/bin/tkn /usr/local/bin/kubectl-tkn
#    tags:
#     - cicd
            
  - name: Install pip
    package: name=python3-pip
    tags:
     - cicd  
  - name: install pip3 to run ansible module kubernetes.core.k8s  
    shell: pip3 install kubernetes
    tags:
     - cicd   
     
  - name: ingress for tekton dashboard
    kubernetes.core.k8s:
     state: present
     definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: tkndashoboard-ingress
        namespace: tekton-pipelines
      spec:
       rules:
        - http:
           paths:
            - path: /
              host: "tkn.mylocaldomain"
              pathType: Prefix
              backend:
               service:
                name: tekton-dashboard   
                port: 
                 number: 9097
    tags:
     - cicd      
     
  - name: install tkn triggers
    shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/release.yaml
    tags:
     - cicd     
  - name: install tkn interceptors
    shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/previous/v0.17.1/interceptors.yaml
    tags:
     - cicd        

     
     

   
    
    

    
     
     