---
 - name: Create npm trigger binding
   kubernetes.core.k8s:
    state: present
    definition:    
     apiVersion: triggers.tekton.dev/v1beta1
     kind: TriggerBinding
     metadata:
      name: github-npmpush-binding
      namespace: mfpipeline
     spec:
      params:
       - name: commitid
         value: $(body.head_commit.id)
       - name: gitrepositoryurl
         value: $(body.repository.clone_url) 
       - name: reponame
         value: $(body.repository.name)          
   tags:
    - pipeline_trigger           
         
 - name: Create npm trigger template
   kubernetes.core.k8s:
    state: present
    definition:                  
      apiVersion: triggers.tekton.dev/v1beta1
      kind: TriggerTemplate
      metadata:
        name: github-npmpush-template
        namespace: mfpipeline
      spec:
        params:
        - name: commitid
          description: The Image Tag of the Container Image
          default: dev
        - name: gitrepositoryurl
          description: The git repository url
        - name: reponame
          description: The name of the git repository       
        resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: generic-npm-pipe
          spec:
            pipelineRef:
              name: npmpipeline
            params:
            - name: jobname
              value: $(tt.params.reponame)           
            - name: gitrepositoryurl
              value: $(tt.params.gitrepositoryurl)
            - name: commitid
              value: $(tt.params.commitid) 
            - name: gitrevision
              value: dev                             
            workspaces:
             - name: shared-workspace
               persistentVolumeClaim:
                claimName: tkn-workspace-claim
             - name: maven-settings
               persistentVolumeClaim:
                claimName: tkn-workspace-claim  
             - name: cdrepo
               persistentVolumeClaim:
                claimName: tkn-deployrepo-claim      
             - name: git-config
               persistentVolumeClaim:
                claimName: tkn-workspace-claim                           
   tags:
    - pipeline_trigger  
  
 - name: Create EventListener
   kubernetes.core.k8s:
    state: present
    definition:      
      apiVersion: triggers.tekton.dev/v1beta1
      kind: EventListener
      metadata:
        name: github-new-npmpush-listener
        namespace: mfpipeline
      spec:
        triggers:
          - name: github-new-npmpush-listener
            interceptors:
              - ref:
                  name: "github"
                params:
                  - name: "secretRef"
                    value:
                      secretName: github-secret
                      secretKey: secretToken
                  - name: "eventTypes"
                    value: ["push"]
              - name: "only deploy on pushes to main branch"
                ref:
                  name: "cel"
                params:
                  - name: "filter"
                    value: "body.ref in ['refs/heads/dev']"
            bindings:
              - ref: github-npmpush-binding
            template:
              ref: github-npmpush-template
        resources:
          kubernetesResource:
            spec:
              template:
                spec:
                  containers:
                    - resources:
                        requests:
                          memory: "64Mi"
                          cpu: "250m"
                        limits:
                          memory: "128Mi"
                          cpu: "500m"    
   tags:
    - pipeline_trigger        
 
 - name: Create ingress for npm eventlistener
   kubernetes.core.k8s:
    state: present
    definition:                                                
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: npmpushlistener-ingress
        namespace: mfpipeline
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        rules:
        - http:
            paths:
            - path: /pushnpm
              pathType: Prefix
              backend:
                service:
                  name: el-github-new-npmpush-listener
                  port:
                    number: 8080 
   tags:
    - pipeline_trigger  