---             
 - name: Create pipeline
   kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: mavenpipeline
        namespace: mfpipeline
      spec:
        params:
         - name: commitid
           description: The git commitid
         - name: gitrevision
           description: The git revision
           default: dev           
         - name: gitrepositoryurl
           description: The git repository url
           default: https://github.com/myfinance/mfframework.git
         - name: jobname
           description: The name of the job and subdirectory in the workspace
           default: mfframework                          
         - name: MVN_REPO
           type: string
           default: "http://192.168.100.73:31001/repository/maven-releases/"     
         - name: Container_REPO
           type: string
           default: "192.168.100.73:31003/repository/mydockerrepo/"                                                      
        workspaces:
         - name: shared-workspace
         - name: maven-settings
        tasks:
         - name: clone-sources
           taskRef:
            name: git-clone
           params:
            - name: url
              value: $(params.gitrepositoryurl)
            - name: revision 
              value: $(params.gitrevision)
            - name: deleteExisting
              value: 'true'
            - name: submodules
              value: "false"
            - name: subdirectory
              value: $(params.jobname)
           workspaces:
            - name: output
              workspace: shared-workspace
         - name: getversion
           taskRef:
            name: getversion
           params:
            - name: CONTEXT_DIR
              value: $(params.jobname)            
           workspaces:
            - name: source
              workspace: shared-workspace            
           runAfter:
            - clone-sources                             
         - name: maven-set-version
           taskRef:
            name: maven
           params:
            - name: CONTEXT_DIR
              value: $(params.jobname)            
            - name: MAVEN_IMAGE
              value: maven:3.8.4-eclipse-temurin-17-alpine
            - name: GOALS 
              value: 
              - versions:set
              - -DnewVersion=$(tasks.getversion.results.version)$(params.commitid)
           runAfter:
            - getversion
           workspaces:
            - name: maven-settings
              workspace: maven-settings              
            - name: source
              workspace: shared-workspace                       
         - name: maven-build
           taskRef:
            name: maven
           params:
            - name: CONTEXT_DIR
              value: $(params.jobname)
            - name: MAVEN_IMAGE
              value: maven:3.8.4-eclipse-temurin-17-alpine
            - name: GOALS 
              value: 
              - clean
              - -DtargetRepository=$(params.MVN_REPO)
              - deploy
           runAfter:
            - maven-set-version
           workspaces:
            - name: maven-settings
              workspace: maven-settings              
            - name: source
              workspace: shared-workspace    
         - name: container-build
           taskRef:
            name: maven
           params:
            - name: CONTEXT_DIR
              value: $(params.jobname)
            - name: MAVEN_IMAGE
              value: maven:3.8.4-eclipse-temurin-17-alpine                 
            - name: GOALS 
              value: 
              - package
              - jib:build
              - -Djib.container-repo=$(params.Container_REPO) 
           runAfter:
            - maven-build
           workspaces:
            - name: maven-settings
              workspace: maven-settings              
            - name: source
              workspace: shared-workspace  
         - name: helm-upgrade
           taskRef:
            name: helm-upgrade-from-source
           params:
            - name: charts_dir
              value: $(params.jobname)/helm
            - name: release_version
              value: $(tasks.getversion.results.version)$(params.commitid)
            - name: release_name
              value: "mfcomposite"
            - name: overwrite_values
              value: "image.version=$(tasks.getversion.results.version)$(params.commitid), stage=dev, mfcomposite.mf_http_port_ext=30028, repository=192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-"
            - name: release_namespace
              value: mfdev
           workspaces:
            - name: source
              workspace: shared-workspace
           runAfter:
            - container-build                                                               
   tags:
    - myf_pipeline   
    
 - name: Create mfdev ns
   kubernetes.core.k8s:
    name: mfdev
    api_version: v1
    kind: Namespace
    state: present
   tags:
    - myf_pipeline    
       
