---
 - name: Create a k8s namespace
   kubernetes.core.k8s:
    name: mfpipeline
    api_version: v1
    kind: Namespace
    state: present
   tags:
    - pipeline_prepare
    
 - name: Create PV
   kubernetes.core.k8s:
    definition:
     apiVersion: v1
     kind: PersistentVolume
     metadata:
      name: tkn-workspace
     spec:
      storageClassName: tknstorage
      accessModes:
       - ReadWriteOnce
      capacity:
       storage: 1Gi
      hostPath:
       path: /mnt/data/tkn/
       type: DirectoryOrCreate 
    state: present
   tags:
    - pipeline_prepare  
    
 - name: Create PVC
   kubernetes.core.k8s:
    definition:   
     apiVersion: v1
     kind: PersistentVolumeClaim
     metadata:
      name: tkn-workspace-claim
      namespace: mfpipeline
     spec:
      storageClassName: tknstorage
      accessModes:
       - ReadWriteOnce
      resources:
       requests:
        storage: 1Gi    
    state: present
   tags:
    - pipeline_prepare  
    
 - name: Download git-clone-task to the cluster.
   ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml 
    dest: ~/git-clone.yaml
    mode: '0664'
   tags:
    - pipeline_prepare     

 - name: Apply git-clone-task to the cluster.
   kubernetes.core.k8s:
    state: present
    namespace: mfpipeline
    src: ~/git-clone.yaml 
   tags:
    - pipeline_prepare  
    
 - name: Download maven-task to the cluster.
   ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/catalog/main/task/maven/0.2/maven.yaml
    dest: ~/maven.yaml
    mode: '0664'
   tags:
    - pipeline_prepare     

 - name: Apply maven-task to the cluster.
   kubernetes.core.k8s:
    state: present
    namespace: mfpipeline
    src: ~/maven.yaml 
   tags:
    - pipeline_prepare  
    
 - name: Download buildah-task to the cluster.
   ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.2/buildah.yaml
    dest: ~/buildah.yaml
    mode: '0664'
   tags:
    - pipeline_prepare     

 - name: Apply buildah-task to the cluster.
   kubernetes.core.k8s:
    state: present
    namespace: mfpipeline
    src: ~/buildah.yaml 
   tags:
    - pipeline_prepare  
    
 - name: Download helm-task to the cluster.
   ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/catalog/main/task/helm-upgrade-from-source/0.3/helm-upgrade-from-source.yaml
    dest: ~/helm.yaml
    mode: '0664'
   tags:
    - pipeline_prepare     

 - name: Apply helm-task to the cluster.
   kubernetes.core.k8s:
    state: present
    namespace: mfpipeline
    src: ~/helm.yaml 
   tags:
    - pipeline_prepare  
    
 - name: Download generate-build-id-task to the cluster.
   ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/catalog/main/task/generate-build-id/0.1/generate-build-id.yaml
    dest: ~/generate-build-id.yaml
    mode: '0664'
   tags:
    - pipeline_prepare     

 - name: Apply generate-build-id-task to the cluster.
   kubernetes.core.k8s:
    state: present
    namespace: mfpipeline
    src: ~/generate-build-id.yaml 
   tags:
    - pipeline_prepare  