---
  #- name: upgrade all packages
  #  yum:
  #   name: '*'
  #   state: latest
  #   exclude: kernel*
  - name: Install some base dnf package for git compile etc
    dnf:
     name: "{{ item }}"
    with_items:
     #allgemein hilfreiche tools
     - tree
     - wget
     #needed for nfs
     - nfs-utils
