---
# tasks file for sonar
- name: create dir for docker
  file: path=/home/{{username}}/docker
    state=directory
  tags:
  - sonar
- name: create dir for sonar docker compose
  file: path=/home/{{username}}/docker/sonar
    state=directory
  tags:
  - sonar
- name: copy docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{username}}/docker/sonar/docker-compose.yml"
    owner: "{{username}}"
  tags:
  - sonar
#install myfinance to be sure that volumes are created
- name: run the service for sonar defined in docker-compose.yml
  shell: docker stack deploy -c /home/{{username}}/docker/sonar/docker-compose.yml sonar
  tags:
  - sonar
- name: remove sonar service
  shell: docker stack rm sonar && sleep 20
  tags:
  - sonar
- name: run the service for sonar in docker-compose.yml
  shell: docker stack deploy -c /home/{{username}}/docker/sonar/docker-compose.yml sonar
  tags:
  - sonar
