---
# vars file for buildServer
  # vars for java maven
  download_folder: /mnt/data/software/
  java_pkg: "java-11-openjdk-devel"
  maven_version: "3.5.4"
  maven_tar: "{{download_folder}}maven/apache-maven-{{maven_version}}-bin.tar.gz"
  # vars for build user
  username: "holger"
  password: "$6$7SHA512PW"
