---
  - name: Add the user
    user:
     name: '{{username}}'
     comment: the user builder
     uid: 1001
     #add docker group
     groups: wheel,docker
     password: '{{password}}'
    tags:
     - builduser     
  - name: Log into DockerHub
    shell: "docker login -u {{docker.user}} -p {{docker.password}}"   
    become: yes
    become_user: "{{username}}"
    tags:
     - builduser            
