---
managed_prefix: "ansible_"

managed_ip_hosts:
  - name: "ansible_DHCP_Clients"
    type: "range"
    start: "192.168.100.100"
    end: "192.168.100.240"
  - name: "ansible_PC-Paul"
    type: "ip"
    ip: "192.168.100.241"