---
- name: Set DHCP Server Configuration
  sophos.sophos_firewall.sfos_xmlapi:
    xml_tag: DHCPServer
    state: updated
    data: |
      <DHCPServer>
        <Name>{{ dhcp_config.name }}</Name>
        <Status>1</Status>
        <Interface>{{ dhcp_config.interface }}</Interface>
        <IPLease>
          <IP>{{ dhcp_config.lease_range }}</IP>
        </IPLease>
        <StaticLease>
          {% for lease in dhcp_config.static_leases %}
          <Lease>
            <HostName>{{ lease.name }}</HostName>
            <MACAddress>{{ lease.mac }}</MACAddress>
            <IPAddress>{{ lease.ip }}</IPAddress>
          </Lease>
          {% endfor %}
        </StaticLease>
        <ConflictDetection>Disable</ConflictDetection>
        <LeaseForRelay>Disable</LeaseForRelay>
        <SubnetMask>255.255.255.0</SubnetMask>
        <DefaultLeaseTime>1440</DefaultLeaseTime>
        <MaxLeaseTime>2880</MaxLeaseTime>
        <UseApplianceDNSSettings>Disable</UseApplianceDNSSettings>
        <PrimaryDNSServer>{{ dhcp_config.dns_primary }}</PrimaryDNSServer>
        <SecondaryDNSServer>{{ dhcp_config.dns_secondary }}</SecondaryDNSServer>
        <Gateway>{{ dhcp_config.gateway }}</Gateway>
        <UseInterfaceIPasGateway>UseInterfaceIPAsGateway</UseInterfaceIPasGateway>
      </DHCPServer>
  vars:
    ansible_connection: httpapi
    ansible_network_os: sophos.sophos_firewall.sfos
